#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v21
# autospec commit: fbbd4e3
#
Name     : R-mixtools
Version  : 2.0.0.1
Release  : 56
URL      : https://ftp.osuosl.org/pub/cran/src/contrib/mixtools_2.0.0.1.tar.gz
Source0  : https://ftp.osuosl.org/pub/cran/src/contrib/mixtools_2.0.0.1.tar.gz
Summary  : Tools for Analyzing Finite Mixture Models
Group    : Development/Tools
License  : GPL-2.0+
Requires: R-mixtools-lib = %{version}-%{release}
Requires: R-kernlab
Requires: R-plotly
Requires: R-scales
Requires: R-segmented
BuildRequires : R-kernlab
BuildRequires : R-plotly
BuildRequires : R-scales
BuildRequires : R-segmented
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
No detailed description available

%package lib
Summary: lib components for the R-mixtools package.
Group: Libraries

%description lib
lib components for the R-mixtools package.


%prep
%setup -q -n mixtools
pushd ..
cp -a mixtools buildavx2
popd
pushd ..
cp -a mixtools buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1742476271

%install
export SOURCE_DATE_EPOCH=1742476271
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
R CMD check --no-manual --no-examples --no-codoc --no-vignettes mixtools || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/mixtools/CITATION
/usr/lib64/R/library/mixtools/DESCRIPTION
/usr/lib64/R/library/mixtools/INDEX
/usr/lib64/R/library/mixtools/Meta/Rd.rds
/usr/lib64/R/library/mixtools/Meta/data.rds
/usr/lib64/R/library/mixtools/Meta/features.rds
/usr/lib64/R/library/mixtools/Meta/hsearch.rds
/usr/lib64/R/library/mixtools/Meta/links.rds
/usr/lib64/R/library/mixtools/Meta/nsInfo.rds
/usr/lib64/R/library/mixtools/Meta/package.rds
/usr/lib64/R/library/mixtools/Meta/vignette.rds
/usr/lib64/R/library/mixtools/NAMESPACE
/usr/lib64/R/library/mixtools/NEWS
/usr/lib64/R/library/mixtools/R/mixtools
/usr/lib64/R/library/mixtools/R/mixtools.rdb
/usr/lib64/R/library/mixtools/R/mixtools.rdx
/usr/lib64/R/library/mixtools/data/CO2data.RData
/usr/lib64/R/library/mixtools/data/Habituationdata.RData
/usr/lib64/R/library/mixtools/data/NOdata.RData
/usr/lib64/R/library/mixtools/data/RTdata.RData
/usr/lib64/R/library/mixtools/data/RTdata2.RData
/usr/lib64/R/library/mixtools/data/RanEffdata.RData
/usr/lib64/R/library/mixtools/data/RodFramedata.RData
/usr/lib64/R/library/mixtools/data/Waterdata.RData
/usr/lib64/R/library/mixtools/data/WaterdataFull.RData
/usr/lib64/R/library/mixtools/data/tonedata.RData
/usr/lib64/R/library/mixtools/doc/index.html
/usr/lib64/R/library/mixtools/doc/mixtools.R
/usr/lib64/R/library/mixtools/doc/mixtools.Rnw
/usr/lib64/R/library/mixtools/doc/mixtools.pdf
/usr/lib64/R/library/mixtools/help/AnIndex
/usr/lib64/R/library/mixtools/help/aliases.rds
/usr/lib64/R/library/mixtools/help/figures/mixtools.png
/usr/lib64/R/library/mixtools/help/mixtools.rdb
/usr/lib64/R/library/mixtools/help/mixtools.rdx
/usr/lib64/R/library/mixtools/help/paths.rds
/usr/lib64/R/library/mixtools/html/00Index.html
/usr/lib64/R/library/mixtools/html/R.css

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/mixtools/libs/mixtools.so
/V4/usr/lib64/R/library/mixtools/libs/mixtools.so
/usr/lib64/R/library/mixtools/libs/mixtools.so
